# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int
#     system_prompt: str optional (add system instruction when generating model answer)

gpt-3.5-turbo-0125:
    model_name: gpt-3.5-turbo-0125
    endpoints: null
    api_type: openai
    parallel: 16

gpt-4o-2024-11-20:
    model_name: gpt-4o-2024-11-20
    endpoints: null
    api_type: openai
    parallel: 16

lightblue__qarasu-refreshed:
    model_name: lightblue/qarasu-refreshed
    endpoints:
        - api_base: http://0.0.0.0:8000/v1
          api_key: abcde
    api_type: openai
    parallel: 16
    system_prompt: You are a helpful assistant

Qwen__Qwen2.5-7B-Instruct:
    model_name: Qwen/Qwen2.5-7B-Instruct
    endpoints:
        - api_base: http://0.0.0.0:8000/v1
          api_key: abcde
    api_type: openai
    parallel: 64

gpt-4-0314:
    model_name: gpt-4-0314
    endpoints: null
    api_type: openai
    parallel: 8

gpt-4-1106-preview:
    model_name: gpt-4-1106-preview
    endpoints: null
    api_type: openai
    parallel: 8
